version: "3"
services:
  nestjs:
    build: ./
    env_file:
      - .env.production
    ports:
      - "8001:8001"
    networks:
      - my_network
    volumes:
      - ./app:/usr/app
  nginx:
    build: ./nginx
    ports:
      - "3001:3001"
    networks:
      - my_network
    volumes:
      - ./nginx/config:/etc/nginx/conf.d

networks:
  my_network:
    driver: bridge
